# Generated by Django 4.2.16 on 2026-09-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COSOLVERS_app', '0006_remove_comment_rating_problem_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
