# Generated by Django 4.2.16 on 2026-09-30 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('COSOLVERS_app', '0008_repair_userprofile_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
