# Generated by Django 4.2.16 on 2026-09-30 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('COSOLVERS_app', '0009_alter_problem_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
